import Sidebar from "./components/Sidebar";
import  Header from './components/Header'
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div className="flex justify-between">
          <div className="fixed w-full "> <Header /></div>
         
          <div className="w-[100px] max-sm:hidden">
            <Sidebar />
          </div>

          <div className="w-full mt-[100px]">{children}</div>
        </div>
      </body>
    </html>
  );
}
