import Sidebar from "./components/Sidebar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-between">
          <div className="w-[150px]">
            <div className="fixed h-screen w-[125px] lg:w-[130px]">
              <Sidebar />
            </div>
          </div>

          <div className="w-full">
            <div className="bg-red-700">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
